version: '3'

services:
  node:
    build: ./node/
    expose:
      - "6001"
    volumes:
      - ${WORKSPACES}:/var/www/html/:rw,cached
    links:
      - redis:redis
    extra_hosts:
      - "local.zz.com:${NGINX_IP}"
    networks:
      docker_net:
        ipv4_address: ${NODE_IP}
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${WORKSPACES}:/var/www/html/:rw,cached
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro,cached
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro,cached
      - ./log/nginx/:/var/log/nginx/:rw,cached
    links:
      - php:fpm
    environment:
      - TZ=Asia/Shanghai
    networks:
      docker_net:
        ipv4_address: ${NGINX_IP}

  php:
    build: ./php/
    expose:
      - "9000"
    volumes:
      - ${WORKSPACES}:/var/www/html/:rw,cached
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro,cached
      - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw,cached
      - ./log/php-fpm/:/var/log/php-fpm/:rw,cached
    links:
      - mysql:mysql
      - redis:redis
    networks:
      docker_net:
        ipv4_address: ${PHP_IP}

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro,cached
      - ./mysql/data:/var/lib/mysql/:rw,cached
      - ./log/mysql/:/var/log/mysql/:rw,cached
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    networks:
      docker_net:
        ipv4_address: ${MYSQL_IP}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    command:
      redis-server --requirepass scztskj
    networks:
      docker_net:
        ipv4_address: ${REDIS_IP}

networks:
  docker_net:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: "${DOCKER_SUBNET}"